"""memory ledger

Revision ID: d2daa832397f
Revises: 46a9e6d8e164
Create Date: 2026-09-28 08:59:35.759373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2daa832397f"
down_revision: str | Sequence[str] | None = "46a9e6d8e164"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_ledger_turns",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("engine", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.BigInteger(), nullable=True),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("assistant_message", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recalled_memory_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_memory_ledger_turns_user_id"),
        "memory_ledger_turns",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "memory_ledger_writes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=False),
        sa.Column("memory_id", sa.String(length=255), nullable=False),
        sa.Column("event", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["memory_ledger_turns.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_ledger_writes_memory_id"),
        "memory_ledger_writes",
        ["memory_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_memory_ledger_writes_memory_id"), table_name="memory_ledger_writes"
    )
    op.drop_table("memory_ledger_writes")
    op.drop_index(
        op.f("ix_memory_ledger_turns_user_id"), table_name="memory_ledger_turns"
    )
    op.drop_table("memory_ledger_turns")
    # ### end Alembic commands ###
